import { promises as fs } from "node:fs";
import JSZip from "jszip";
import { prisma } from "../database/prismaClient";
import { AppError } from "../middleware/error.middleware";
import { courseRepository } from "../repositories/course.repository";
import { reportPdfService } from "./reportPdf.service";
import { rubricService, RubricCriteria } from "./rubric.service";
import { blueprintService } from "./blueprint.service";
import { logger } from "../utils/logger";
import { auditService } from "./audit.service";

const safe = (name: string) => name.replace(/[^\w.\- ]+/g, "_").trim();

/**
 * One ZIP with everything a moderation / accreditation reviewer asks for:
 * syllabus, papers, latest report PDFs per paper, marking schemes, blueprint,
 * CO list and an index README. Files are read from disk; missing ones are noted, not fatal.
 */
export const courseFileService = {
  async build(facultyId: number, courseId: number): Promise<{ buffer: Buffer; filename: string }> {
    const owned = await courseRepository.findOwnedById(courseId, facultyId);
    if (!owned) throw new AppError("Course not found", 404);
    const course = await prisma.course.findUniqueOrThrow({
      where: { id: courseId },
      include: {
        syllabusDocuments: { orderBy: { uploadedAt: "desc" }, take: 1 },
        courseOutcomes: { orderBy: { code: "asc" } },
        questionPapers: {
          orderBy: [{ year: "desc" }, { uploadedAt: "desc" }],
          include: { reports: { orderBy: { createdAt: "desc" }, select: { id: true, reportType: true, createdAt: true } }, _count: { select: { questions: true, studentMarks: true } } },
        },
        rubrics: { orderBy: { createdAt: "desc" } },
        lecturePlans: { orderBy: { createdAt: "desc" }, take: 1 },
      },
    });

    const zip = new JSZip();
    const index: string[] = [
      `# Course file — ${course.courseCode} ${course.courseName}`,
      "",
      `Generated by AcadIQ on ${new Date().toISOString().slice(0, 10)}. AI-generated content is labelled as such and was reviewed by faculty before adoption.`,
      "",
      "## Contents",
    ];
    const missing: string[] = [];

    const addFile = async (zipPath: string, diskPath: string) => {
      try {
        zip.file(zipPath, await fs.readFile(diskPath));
        index.push(`- ${zipPath}`);
      } catch {
        missing.push(zipPath);
      }
    };

    // 1. Syllabus + outcomes
    const syllabus = course.syllabusDocuments[0];
    if (syllabus) await addFile(`01-syllabus/${safe(syllabus.originalName)}`, syllabus.filePath);
    if (course.courseOutcomes.length) {
      zip.file("01-syllabus/course-outcomes.md", ["# Course outcomes", "", ...course.courseOutcomes.map((o) => `- **${o.code}** — ${o.description}`), ""].join("\n"));
      index.push("- 01-syllabus/course-outcomes.md");
    }

    // 2. Blueprint
    const blueprint = await blueprintService.get(facultyId, courseId);
    zip.file(
      "02-blueprint/exam-blueprint.json",
      JSON.stringify({ ...blueprint, note: blueprint.isDefault ? "No blueprint saved; default distribution shown." : undefined }, null, 2)
    );
    index.push("- 02-blueprint/exam-blueprint.json");

    // 3. Papers + reports
    for (const paper of course.questionPapers) {
      const folder = `03-papers/${paper.year}-${safe(paper.semester)}`;
      await addFile(`${folder}/${safe(paper.originalName)}`, paper.filePath);
      const latestByType = new Map<string, (typeof paper.reports)[number]>();
      for (const report of paper.reports) if (!latestByType.has(report.reportType)) latestByType.set(report.reportType, report);
      for (const report of latestByType.values()) {
        try {
          const { buffer, filename } = await reportPdfService.render(report.id, facultyId);
          zip.file(`${folder}/reports/${safe(filename)}`, buffer);
          index.push(`- ${folder}/reports/${safe(filename)}`);
        } catch (error) {
          logger.warn("course_file_report_pdf_failed", { reportId: report.id, reason: error instanceof Error ? error.message : String(error) });
          missing.push(`${folder}/reports/report-${report.id}.pdf`);
        }
      }
      if (paper._count.studentMarks) {
        const marks = await prisma.studentMark.findMany({ where: { paperId: paper.id }, include: { question: { select: { sequenceNumber: true } } } });
        const seqs = [...new Set(marks.map((m) => m.question.sequenceNumber))].sort((a, b) => a - b);
        const byStudent = new Map<string, Map<number, number>>();
        for (const m of marks) {
          const row = byStudent.get(m.studentIdentifier) ?? new Map<number, number>();
          row.set(m.question.sequenceNumber, Number(m.marks));
          byStudent.set(m.studentIdentifier, row);
        }
        const csv = [["student", ...seqs.map((s) => `Q${s}`)].join(","), ...[...byStudent.entries()].map(([student, row]) => [JSON.stringify(student), ...seqs.map((s) => row.get(s) ?? "")].join(","))].join("\n");
        zip.file(`${folder}/marks.csv`, csv);
        index.push(`- ${folder}/marks.csv (${byStudent.size} students)`);
      }
    }

    // 4. Marking schemes
    for (const rubric of course.rubrics) {
      const criteria = rubric.criteria as unknown as Partial<RubricCriteria>;
      if (!criteria?.questions) continue;
      const { filename, content } = await rubricService.markdown(facultyId, rubric.id);
      zip.file(`04-marking-schemes/${safe(filename)}`, content);
      index.push(`- 04-marking-schemes/${safe(filename)}`);
    }

    // 5. Lecture plan
    const plan = course.lecturePlans[0];
    if (plan) {
      const json = plan.planJson as { title?: string; weeks?: Array<{ week: number; title: string; topics: string[]; outcomes: string[]; assessment: string | null }> };
      const lines = [`# ${json.title ?? "Lecture plan"}`, "", `${plan.weeks} weeks × ${plan.hoursPerWeek} h · AI-drafted ${plan.createdAt.toISOString().slice(0, 10)}`, "", "| Week | Title | Topics | COs | Assessment |", "|---|---|---|---|---|"];
      for (const w of json.weeks ?? []) lines.push(`| ${w.week} | ${w.title} | ${w.topics.join("; ")} | ${w.outcomes.join(", ")} | ${w.assessment ?? ""} |`);
      zip.file("05-lecture-plan/lecture-plan.md", lines.join("\n"));
      index.push("- 05-lecture-plan/lecture-plan.md");
    }

    if (missing.length) index.push("", "## Not included (file missing on server)", ...missing.map((m) => `- ${m}`));
    zip.file("README.md", `${index.join("\n")}\n`);

    await auditService.recordAuditLog({ userId: facultyId, action: "Faculty exported course file", document: `course:${courseId}` });
    const buffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    return { buffer, filename: `${safe(course.courseCode)}-course-file-${new Date().toISOString().slice(0, 10)}.zip` };
  },
};
